language: php
php:
  - '5.6'

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --no-interaction

# Commands you want to run that will verify your build.
script: phpunit tests

notifications:
    on_success: change
    on_failure: always
